include:
  - node.base
  - node.npm
  - node.yarn
  - node.pumpio
  - node.offandonagain-org
  - node.fulldom
  - node.lazymention
  - node.gh-pages-server
  - node.pumabot
  - node.gradlebot
  - node.dev
